
# baseurl: ""
# url: "https://terborch.github.io/SFF/"


title: Farm Energy System
description: >- # Included in Google sear
  Farm Energy System modelling in the context of the EPFL master thesis titled
  Energetic Environmental Economic Optimization of a Farm 
  Case study: Swiss Future Farm 
  by Nils Ter-borch 2020
github_username: terborch

# Email and twitter are optional:
email: n.terborch@protonmail.ch

# Everything below here can be ignored, unless you want to change the theme entirely
theme: jekyll-theme-cayman

