title: Farm Energy System modelling
email: n.terborch@protonmail.ch
description: >- # Included in Google sear
  Farm Energy System modelling in the context of the EPFL master thesis titled
  Energetic Environmental Economic Optimization of a Farm 
  Case study: Swiss Future Farm 
  by Nils Ter-borch 2020
baseurl: ""
url: "https://terborch.github.io/SFF/"





theme: jekyll-theme-cayman
